// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "dnd_schedule/internal/domain/models"

	time "time"
)

// MockIDatasource is an autogenerated mock type for the IDatasource type
type MockIDatasource struct {
	mock.Mock
}

type MockIDatasource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatasource) EXPECT() *MockIDatasource_Expecter {
	return &MockIDatasource_Expecter{mock: &_m.Mock}
}

// AddDemands provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasource) AddDemands(ctx context.Context, _a1 []models.Demand) ([]models.Demand, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddDemands")
	}

	var r0 []models.Demand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Demand) ([]models.Demand, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.Demand) []models.Demand); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Demand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.Demand) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasource_AddDemands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDemands'
type MockIDatasource_AddDemands_Call struct {
	*mock.Call
}

// AddDemands is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 []models.Demand
func (_e *MockIDatasource_Expecter) AddDemands(ctx interface{}, _a1 interface{}) *MockIDatasource_AddDemands_Call {
	return &MockIDatasource_AddDemands_Call{Call: _e.mock.On("AddDemands", ctx, _a1)}
}

func (_c *MockIDatasource_AddDemands_Call) Run(run func(ctx context.Context, _a1 []models.Demand)) *MockIDatasource_AddDemands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Demand))
	})
	return _c
}

func (_c *MockIDatasource_AddDemands_Call) Return(_a0 []models.Demand, _a1 error) *MockIDatasource_AddDemands_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasource_AddDemands_Call) RunAndReturn(run func(context.Context, []models.Demand) ([]models.Demand, error)) *MockIDatasource_AddDemands_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDemands provides a mock function with given fields: ctx, demandIDs
func (_m *MockIDatasource) DeleteDemands(ctx context.Context, demandIDs []int) error {
	ret := _m.Called(ctx, demandIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDemands")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, demandIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasource_DeleteDemands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDemands'
type MockIDatasource_DeleteDemands_Call struct {
	*mock.Call
}

// DeleteDemands is a helper method to define mock.On call
//   - ctx context.Context
//   - demandIDs []int
func (_e *MockIDatasource_Expecter) DeleteDemands(ctx interface{}, demandIDs interface{}) *MockIDatasource_DeleteDemands_Call {
	return &MockIDatasource_DeleteDemands_Call{Call: _e.mock.On("DeleteDemands", ctx, demandIDs)}
}

func (_c *MockIDatasource_DeleteDemands_Call) Run(run func(ctx context.Context, demandIDs []int)) *MockIDatasource_DeleteDemands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockIDatasource_DeleteDemands_Call) Return(_a0 error) *MockIDatasource_DeleteDemands_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasource_DeleteDemands_Call) RunAndReturn(run func(context.Context, []int) error) *MockIDatasource_DeleteDemands_Call {
	_c.Call.Return(run)
	return _c
}

// GetDemands provides a mock function with given fields: ctx, week
func (_m *MockIDatasource) GetDemands(ctx context.Context, week time.Time) ([]models.Demand, error) {
	ret := _m.Called(ctx, week)

	if len(ret) == 0 {
		panic("no return value specified for GetDemands")
	}

	var r0 []models.Demand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]models.Demand, error)); ok {
		return rf(ctx, week)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []models.Demand); ok {
		r0 = rf(ctx, week)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Demand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, week)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasource_GetDemands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDemands'
type MockIDatasource_GetDemands_Call struct {
	*mock.Call
}

// GetDemands is a helper method to define mock.On call
//   - ctx context.Context
//   - week time.Time
func (_e *MockIDatasource_Expecter) GetDemands(ctx interface{}, week interface{}) *MockIDatasource_GetDemands_Call {
	return &MockIDatasource_GetDemands_Call{Call: _e.mock.On("GetDemands", ctx, week)}
}

func (_c *MockIDatasource_GetDemands_Call) Run(run func(ctx context.Context, week time.Time)) *MockIDatasource_GetDemands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIDatasource_GetDemands_Call) Return(_a0 []models.Demand, _a1 error) *MockIDatasource_GetDemands_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasource_GetDemands_Call) RunAndReturn(run func(context.Context, time.Time) ([]models.Demand, error)) *MockIDatasource_GetDemands_Call {
	_c.Call.Return(run)
	return _c
}

// GetDemandsByVkID provides a mock function with given fields: ctx, week, vkID
func (_m *MockIDatasource) GetDemandsByVkID(ctx context.Context, week time.Time, vkID int) ([]models.Demand, error) {
	ret := _m.Called(ctx, week, vkID)

	if len(ret) == 0 {
		panic("no return value specified for GetDemandsByVkID")
	}

	var r0 []models.Demand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]models.Demand, error)); ok {
		return rf(ctx, week, vkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []models.Demand); ok {
		r0 = rf(ctx, week, vkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Demand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, week, vkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasource_GetDemandsByVkID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDemandsByVkID'
type MockIDatasource_GetDemandsByVkID_Call struct {
	*mock.Call
}

// GetDemandsByVkID is a helper method to define mock.On call
//   - ctx context.Context
//   - week time.Time
//   - vkID int
func (_e *MockIDatasource_Expecter) GetDemandsByVkID(ctx interface{}, week interface{}, vkID interface{}) *MockIDatasource_GetDemandsByVkID_Call {
	return &MockIDatasource_GetDemandsByVkID_Call{Call: _e.mock.On("GetDemandsByVkID", ctx, week, vkID)}
}

func (_c *MockIDatasource_GetDemandsByVkID_Call) Run(run func(ctx context.Context, week time.Time, vkID int)) *MockIDatasource_GetDemandsByVkID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockIDatasource_GetDemandsByVkID_Call) Return(_a0 []models.Demand, _a1 error) *MockIDatasource_GetDemandsByVkID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasource_GetDemandsByVkID_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]models.Demand, error)) *MockIDatasource_GetDemandsByVkID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDemands provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasource) UpdateDemands(ctx context.Context, _a1 []models.Demand) ([]models.Demand, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDemands")
	}

	var r0 []models.Demand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Demand) ([]models.Demand, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.Demand) []models.Demand); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Demand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.Demand) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasource_UpdateDemands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDemands'
type MockIDatasource_UpdateDemands_Call struct {
	*mock.Call
}

// UpdateDemands is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 []models.Demand
func (_e *MockIDatasource_Expecter) UpdateDemands(ctx interface{}, _a1 interface{}) *MockIDatasource_UpdateDemands_Call {
	return &MockIDatasource_UpdateDemands_Call{Call: _e.mock.On("UpdateDemands", ctx, _a1)}
}

func (_c *MockIDatasource_UpdateDemands_Call) Run(run func(ctx context.Context, _a1 []models.Demand)) *MockIDatasource_UpdateDemands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Demand))
	})
	return _c
}

func (_c *MockIDatasource_UpdateDemands_Call) Return(_a0 []models.Demand, _a1 error) *MockIDatasource_UpdateDemands_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasource_UpdateDemands_Call) RunAndReturn(run func(context.Context, []models.Demand) ([]models.Demand, error)) *MockIDatasource_UpdateDemands_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatasource creates a new instance of MockIDatasource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatasource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatasource {
	mock := &MockIDatasource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
